
import System.Exception;

public object OutOfBoundsException replicates Exception;

